window:
  title: alacritty
  dynamic_title: true
  opacity: 0.97
  decorations: none
  glyph_offset:
    x: 0
    y: 0
  offset:
    x: 0
    y: 0
  padding:
    x: 0
    y: 0
  dynamic_padding: false
  startup_mode: Maximized

font:
  size: 12

colors:
  # Default colors
  primary:
    background: '0x22272e'
    foreground: '0x768390'

  # Normal colors
  normal:
    black: '0x22272e'
    red: '0xff938a'
    green: '0x6bc46d'
    yellow: '0xc69026'
    blue: '0x6cb6ff'
    magenta: '0xb083f0'
    cyan: '0x56d4dd'
    white: '0x768390'

  # Bright colors
  bright:
    black: '0x636e7b'
    red: '0xff938a'
    green: '0x6bc46d'
    yellow: '0xdaaa3f'
    blue: '0x6cb6ff'
    magenta: '0xdcbdfb'
    cyan: '0x56d4dd'
    white: '0x768390'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xff938a' }
theme: github_dimmed
