#!/bin/bash
# Julio C. Pompa Puente <julio.c.pompa.puente@gmail.com>

if [[ $L6N = 'Scanntech' ]]; then
    git remote | grep -qi scanntech
    [[ $? -eq 0 ]] && \
        git push scanntech master
fi

git push github master

