#!/bin/bash
# Julio C. Pompa Puente <julio.c.pompa.puente@gmail.com>

if [[ $L6N = 'Scanntech' ]]; then
    git remote | grep -qi scanntech
    if [[ $? -eq 0 ]]; then
        GIT_REPO_NAME=`git remote -v | grep -m 1 -E '^scanntech' | \
            rev | cut -d/ -f1 | rev | cut -d' ' -f1`
        [[ $GIT_REPO_NAME = 'notas' ]] && \
            git reset --hard scanntech/master
        git pull scanntech master && \
            exit 0
    fi
fi

git remote | grep -qi github
[[ $? -eq 0 ]] && \
    git pull github master

