" https://github.com/junegunn/vim-plug
call plug#begin('~/.vim/plugged')
	Plug 'bronson/vim-toggle-wrap'
	Plug 'vim-scripts/SearchComplete'
    Plug 'airblade/vim-gitgutter'
    Plug 'itspriddle/vim-shellcheck'
    Plug 'junegunn/fzf.vim'
    Plug 'preservim/nerdtree'
    Plug 'tribela/vim-transparent'

	" tpope
	Plug 'tpope/vim-surround'
    Plug 'tpope/vim-speeddating'
    
    " color themes
    Plug 'wuelnerdotexe/vim-enfocado'
call plug#end()
" - - - - - - - - - 8< - - - - - - - - - 8< - - - - - - - - -

" gitgutter
nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)
let g:gitgutter_terminal_reports_focus=0
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '>'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = '<'

" itspriddle/vim-shellcheck
let g:shellcheck_disable_mappings = 1

"" junegunn/fzf.vim
"let g:fzf_buffers_jump = 1
"let g:fzf_command_prefix = 'Fzf'
"let g:fzf_commits_log_options = '--graph --color=always --format="%C(auto)%h%d %s %C(black)%C(bold)%cr"'
"let g:fzf_preview_window = ['right:60%']

" preservim/nerdtree
nnoremap <C-t> :NERDTreeToggle<CR>
nnoremap <C-f> :NERDTreeFind<CR>
let g:NERDTreeQuitOnOpen = 1
let g:NERDTreeFileLines = 1
" - - - - - - - - - 8< - - - - - - - - - 8< - - - - - - - - -

set updatetime=1000
set nu rnu
set hls
set ignorecase
set cursorline

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smarttab

filetype plugin indent on
syntax on
colorscheme enfocado
set background=dark

autocmd BufWritePre *.* :%s/\s\+$//e

augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

"if has('gui_running')
"  nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>
"  nnoremap <C-F2> :if &go=~#'T'<Bar>set go-=T<Bar>else<Bar>set go+=T<Bar>endif<CR>
"  
"  set guioptions-=m  "remove menu bar
"  set guioptions-=T  "remove toolbar
"
"  set guioptions-=r  "remove right-hand scroll bar
"  set guioptions-=L  "remove left-hand scroll bar
"  
"  "set guifont=Monospace\ 11
"endif

set t_Co=256

