call plug#begin('~/.vim/plugged')
	Plug 'vim-scripts/SearchComplete'
	Plug 'scrooloose/nerdtree'
	Plug 'bronson/vim-toggle-wrap'
    "Plug 'powerline/powerline'
    Plug 'airblade/vim-gitgutter'
    Plug 'hallison/vim-markdown'
    Plug 'freitass/todo.txt-vim'
    Plug 'vim-latex/vim-latex'

    " color themes
	Plug 'sainnhe/vim-color-lost-shrine'
	Plug 'benburrill/potato-colors' 
	Plug 'lithammer/vim-eighties'
	Plug 'aonemd/kuroi.vim'
	
	" tpope
	Plug 'tpope/vim-surround'
    Plug 'tpope/vim-repeat'
    Plug 'tpope/vim-speeddating'
    Plug 'tpope/vim-unimpaired'
    Plug 'tpope/vim-fugitive'
call plug#end()

set nu rnu
set hls
set ignorecase
set cursorline

set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smarttab

syntax on
colorscheme kuroi
set background=dark

" nerdtree
map <F9> :NERDTreeToggle<CR>

" open vimagit pane
nnoremap <leader>gs :Magit<CR>
nnoremap <leader>gP :! git push<CR>

" gitgutter
let g:gitgutter_terminal_reports_focus=0
set updatetime=1000

let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '>'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '^'
let g:gitgutter_sign_modified_removed = '<'

nmap ]h <Plug>(GitGutterNextHunk)
nmap [h <Plug>(GitGutterPrevHunk)

" remove all trailing spaces on save
autocmd BufWritePre *.* :%s/\s\+$//e

augroup numbertoggle
	autocmd!
	autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
	autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END

if has('gui_running')
  nnoremap <C-F1> :if &go=~#'m'<Bar>set go-=m<Bar>else<Bar>set go+=m<Bar>endif<CR>
  nnoremap <C-F2> :if &go=~#'T'<Bar>set go-=T<Bar>else<Bar>set go+=T<Bar>endif<CR>
  
  set guioptions-=m  "remove menu bar
  set guioptions-=T  "remove toolbar

  set guioptions-=r  "remove right-hand scroll bar
  set guioptions-=L  "remove left-hand scroll bar
  
  set guifont=Monospace\ 11
endif

